      correctAnswer: 'A. Un language de programation',    
      correctAnswer: 'B. Un language de programation',
      correctAnswer: 'C. “let” ou “const”',
      correctAnswer: 'A. “let” est utilisé pour déclarer une variable locale à un bloc d’instructions. “const” est utilisé pour déclarer une variable constante qui ne peut pas être réaffectée.',
      correctAnswer: 'B. //',
      correctAnswer: 'B. while (condition) {\r\n    // instructions à répéter\r\n}',
      correctAnswer: 'B.Laravel',
      correctAnswer: 'A. Sa veux dire que c’est un language plus près du language humain',
      correctAnswer: 'C. Search Engine Marketing',
      correctAnswer: ['A. Phyton','B. Ruby']
      correctAnswer: 'A. Importer le contenu d’un fichier dans un script courant',
      correctAnswer: 'A. Java',
      correctAnswer: 'C.HTML et CSS sont des language de balisage tanti que Javascript un language de programation ',     
    correctAnswer: 'Le SEO est l optimisation d un site web pour les moteurs de recherche, visant à améliorer son classement dans les résultats naturels (organiques). Le SEA (Search Engine Advertising) concerne les annonces payantes qui apparaissent en premier dans les résultats des moteurs de recherche.',
      correctAnswer:'C. GET : Utilisée pour récupérer des données d un serveur. Les paramètres sont envoyés dans l URL de la requête ,POST : Utilisée pour envoyer des données au serveur, souvent pour soumettre des formulaires. Les paramètres sont envoyés dans le corps de la requête.'
      correctAnswer: 'B. SQL : Utilise des tables structurées avec des lignes et des colonnes et le langage SQL pour gérer les données. Exemples : MySQL, PostgreSQL.NoSQL : Utilise des structures de données flexibles comme les documents, les graphes, les colonnes, ou les clés-valeurs. Exemples : MongoDB, Cassandra.',
      correctAnswer: 'A. AJAX (Asynchronous JavaScript and XML) est une technique de développement web qui permet de mettre à jour des parties d une page web sans recharger la page entière. Elle utilise JavaScript pour envoyer des requêtes HTTP asynchrones et recevoir des données en arrière-plan.',
      correctAnswer: 'A. HyperText Markup Language',
      correctAnswer: 'B. programmation orientée objet',
      correctAnswer: 'C. C est une extension du langage PHP lui-même.«Extension PHP et référentiel d applications».',
      correctAnswer: 'B. Créer, écrire,chiffrer des données',
      correctAnswer: 'C. les avis, les avertissements et les erreurs fatales',
      correctAnswer: 'A. «==» compare uniquement les valeurs, tandis que «===» compare les valeurs et les types'
      correctAnswer: 'B. class est utilisé pour appliquer des styles à plusieurs éléments qui partagent la même classe, tandis que id est utilisé pour appliquer des styles à un élément unique et doit être unique dans un document HTML. ',
      correctAnswer: 'A. La méthode fetch est utilisée pour effectuer des requêtes réseau pour obtenir des ressources (comme des données JSON) de manière asynchrone.',
      correctAnswer: 'C. Une API REST (Representational State Transfer) est un style architectural pour les services web qui utilise les méthodes HTTP (GET, POST, PUT, DELETE) pour gérer les ressources.',
      correctAnswer: 'A. DOMContentLoaded est un événement qui se déclenche lorsque le document HTML a été complètement chargé et analysé, sans attendre les feuilles de style, les images et les sous-documents.',
      correctAnswer: 'A. Le Virtual DOM est une représentation en mémoire du DOM réel. Lorsqu un composant React est mis à jour, React crée un Virtual DOM, compare cette nouvelle version avec la version précédente, et calcule les différences (diffing). Ensuite, il met à jour uniquement les parties du DOM réel qui ont changé, optimisant ainsi les performances.',
      correctAnswer: 'C. Le Content Security Policy (CSP) est une norme de sécurité qui aide à prévenir les attaques de type XSS (Cross-Site Scripting) en définissant des règles sur les sources autorisées pour les contenus (scripts, images, etc.) chargés sur une page web.',
      correctAnswer: 'B. Le middleware dans un framework backend est une fonction qui a accès à l objet request (req), l objet response (res), et à la fonction next dans le cycle de requête-réponse. Le middleware peut exécuter du code, modifier les objets request et response, et terminer la requête ou passer au middleware suivant dans la pile.',
      correctAnswer: 'B. La sécurité des API implique de protéger les interfaces de programmation contre les accès non autorisés et les attaques. Les meilleures pratiques incluent l utilisation de l authentification et de l autorisation (comme OAuth), le chiffrement des données en transit (TLS), la validation des entrées pour éviter les injections SQL, et la gestion des erreurs de manière sécurisée.',
      correctAnswer: 'B. La commande git rebase permet de déplacer ou de combiner une séquence de commits sur une autre branche. Contrairement à git merge, qui crée un commit de fusion pour combiner les modifications de deux branches, git rebase applique les commits d une branche sur la branche cible de manière linéaire. Cela peut rendre l historique plus propre, mais peut entraîner des conflits qui doivent être résolus au fur et à mesure du processus de rebasage.',
      correctAnswer: 'A. La commande git cherry-pick permet d appliquer un commit spécifique d une branche à une autre. Cela peut être utile pour intégrer des modifications spécifiques sans fusionner toute la branche source. ',
      correctAnswer: 'C.La commande git bisect est utilisée pour identifier le commit spécifique où un bug a été introduit. Git utilise une recherche binaire pour diviser l historique en morceaux plus petits et tester chaque morceau pour isoler le commit problématique.',
      correctAnswer: 'C. JSON',
      correctAnswer: 'B. Django est un framework web open-source pour le langage Python, conçu pour simplifier la création de sites web dynamiques et complexes. Ses principales fonctionnalités incluent une ORM (Object-Relational Mapping) pour interagir avec les bases de données, un système de routage des URL, un moteur de templates pour générer des pages HTML, des outils de gestion de formulaires, et un système d authentification intégré. Django suit le principe "Don"t Repeat Yourself" (DRY) et vise à accélérer le développement tout en favorisant des pratiques de code propres et réutilisables.',
      correctAnswer: 'A. La requête a été réussie et une réponse est renvoyée',
      correctAnswer: 'C. Représentation des États de Transfert',
      correctAnswer: 'C. Pour installer Django, tu peux utiliser pip, le gestionnaire de paquets Python. Exécute la commande pip install django',
      correctAnswer: 'B. GET',
      correctAnswer: 'B. Elle permet de déclencer une action par le clic',
      correctAnswer: '',
      correctAnswer: 'B. <?php echo "Bonjour, monde!"; ?> ',
      correctAnswer: 'A. src',
      correctAnswer: 'C. Un framework PHP pour le développement web',
      correctAnswer: 'B. Un type de donnée qui stocke une séquence de caractères'
      correctAnswer: 'B. Elle affiche un message dans une boîte de dialogue modale',
      correctAnswer: 'A. php artisan migrate',
      correctAnswer: ' B. Un ensemble fini d instructions ou d étapes à suivre pour résoudre un problème ou effectuer une tâche',
      correctAnswer: 'B. Une boucle "for" est utilisée pour un nombre défini d itérations, tandis qu une boucle "while" est utilisée pour un nombre indéfini d itérations',
  